sonar.projectKey=bsterligov_river
sonar.organization=bsterligov

sonar.sources=src
sonar.exclusions=**/target/**,**/*.pb,src/demo-app/**
sonar.sourceEncoding=UTF-8

sonar.coverage.exclusions=src/demo-app/**,src/**/src/main.rs,src/sidecar/src/sink.rs

sonar.rust.lcov.reportPaths=lcov.info
