apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    editable: false

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    editable: false
    jsonData:
      server: clickhouse
      port: 9000
      username: river
      defaultDatabase: river
      traces:
        defaultDatabase: river
        defaultTable: traces
        traceIdColumn: trace_id
        spanIdColumn: span_id
        parentSpanIdColumn: parent_span_id
        serviceNameColumn: service_name
        operationNameColumn: operation_name
        startTimeColumn: start_time_unix_nano
        durationColumn: duration_ns
        durationUnit: nanoseconds
      logs:
        defaultDatabase: river
        defaultTable: logs
        traceIdColumn: trace_id
        spanIdColumn: span_id
        timeColumn: timestamp
        levelColumn: severity_text
        messageColumn: body
    secureJsonData:
      password: river
