name: Pull Request

on:
  pull_request:

concurrency:
  group: pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  MISE_AUTO_INSTALL: false

jobs:
  version:
    name: Calculate Version
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'spec/') }}
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v4
        with:
          install_args: cocogitto

      - name: calculate version
        id: version
        run: |
          VERSION=$(mise run release:version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  rust-quality:
    name: Run Rust Lint & Tests
    runs-on: ubuntu-latest
    needs: version

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v4
        with:
          cache: false
          install_args: rust cargo:cargo-llvm-cov

      - name: fmt check
        run: mise run cargo:fmt-check

      - name: clippy
        run: mise run cargo:clippy

      - name: coverage
        run: mise run cargo:coverage

      - uses: actions/upload-artifact@v7
        with:
          name: lcov
          path: lcov.info
          retention-days: 1

  flutter-quality:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    needs: version

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v4
        with:
          install_args: flutter

      - name: flutter coverage
        run: mise run flutter:coverage

      - uses: actions/upload-artifact@v7
        with:
          name: flutter-lcov
          path: src/ui/coverage/lcov.info
          retention-days: 1

  sonarqube:
    name: Run SonarQube
    runs-on: ubuntu-latest
    needs: [version, rust-quality, flutter-quality]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: lcov

      - uses: actions/download-artifact@v4
        with:
          name: flutter-lcov
          path: src/ui/coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        with:
          args: >-
            -Dsonar.qualitygate.wait=true
            -Dsonar.projectVersion=${{ needs.version.outputs.version }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
